config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v1 do
      resources :highlights, only: [:index, :destroy]
      resources :search, only: [:index]


      # get "/highlights/search", to: "highlights#search"
      # TODO: refactor this to a search controller! index action, highlights is just a param

      # Authentication
      post "/signup", to: "users#create"
      post "/login", to: "auth#create"
      get "/auth", to: "auth#show"

    end
  end

end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/">
        <%= image_tag "soccer-silhouette-image.png", width:30, height: 30, alt: "logo" %>
        Goal Posts
      </a>
      <%= link_to "Home", root_path, style: 'color: #000;' %>
      <%= link_to "Highlights", highlights_path, style: 'color: #000;' %>
      <!-- <%= link_to "Teams", teams_path, style: 'color: #000;' %>
      <% if logged_in? %>
        <%= link_to "Log out", logout_path, method: :delete, style: 'color: #000;' %>
      <% else %>
        <%= link_to "Log in", login_path, style: 'color: #000;' %>
        <%= link_to "Sign up", signup_path, style: 'color: #000;' %>
      <% end %> -->
    </div>
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Goal Posts</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!--  CDN links for jquery DataTables https://datatables.net/ -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.15/datatables.min.css"/>
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.15/datatables.min.js"></script>

    <!-- Bootstrap: ensure proper rendering and touch zooming -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

  </head>

  <body>
    <div class="container" >
      <!--  Nav Bar -->
      <%= render '/layouts/nav' %>

      <!--  Flash messages -->
      <% flash.each do |name, msg|%>
        <div class = "alert alert-<%= name %> alert-dismissable">
          <p> <%=  msg  %></p>
        </div>
      </br>
      <% end %>

      <!--  Page Body -->
      <%= yield %>
      <!--  Footer -->
      <div class="mastfoot">
        <div class="inner">
          <!--  TBD -->
        </div>
      </div>
    </div> <!-- /container -->
  </body>

</html>